<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE system [
    <!ELEMENT system (class)* >
    <!ATTLIST system
        description CDATA   #REQUIRED
    >

    <!ELEMENT class (property | text)* >
    <!ATTLIST class
        fullname    CDATA   #REQUIRED
    >

    <!ELEMENT property EMPTY >
    <!ATTLIST property
        name    CDATA   #REQUIRED
        value   CDATA   #REQUIRED
    >

    <!ELEMENT text (#PCDATA) >
    <!ATTLIST text
        name    CDATA   #REQUIRED
    >
]>

<system description="The MCIV Server.">

    <!-- Properties for the mciv Server -->
	<class fullname="mciv.server.Server">
		<property name="mciv.port" value="1104" />
		<!-- TODO: Investigate static IP (EERO and/or US Internet) -->
		<property name="mcvi.address" value="/174.141.192.202" />
		<property name="mcvi.address.old" value="/23.88.147.138" />
	</class>
	
	<class fullname="sog.util.Concurrent">
		<property name="safeMode" value="true" />
	</class>
 
    <!-- Properties for App -->
    <class fullname="sog.core.App">
        <property name="description" value="Developmental version of application framework" />
        <property name="root" value="/home/sundquis/mciv/sog" />
        <property name="source.dirs" value="/home/sundquis/mciv/sog/src" />
    </class>

    <!-- Properties for Trace -->
	<class fullname="sog.core.Trace">
		<property name="buffer.limit" value="100" />
		<property name="line.limit" value="50000" />
		<property name="file.limit" value="200" />
		<property name="dir.name" value="trace" />
	</class>

	<!--  ByteFile properties on sizes -->
	<class fullname="sog.core.ByteFile">
		<property name="maxLength" value="1000000000" />
		<property name="warnLimit" value="2000000000" />
		<property name="failLimit" value="5000000000" />
	</class>
    
	<class fullname="sog.core.SoftString">
		<property name="threshold" value="50" />
	</class>

	<!--  ByteFile properties on sizes -->
	<class fullname="sog.core.Strings">
		<property name="collection.max.length" value="7" />
		<property name="array.max.length" value="7" />
	</class>

	<class fullname="sog.core.xml.XML">
		<text name="declaration"><![CDATA[<?xml version="1.0" encoding="utf-8"?>]]></text>
	</class>
		
	<class fullname="sog.util.Macro">
		<property name="maxIterations" value="2000" />
	</class>
	
	<class fullname="sog.core.test.Policy">
		<property name="current.policy" value="STRICT" />
	</class>
	

</system>
